#!/usr/bin/env python

##################################################
###          MODULE IMPORT
##################################################
## STANDARD MODULES
from __future__ import print_function
import sys
import argparse
import json
import os

## MODULE IMPORT
from pdfigcapx import logger

###############################
###      LIST OF KEYWORDS
###############################
def select_default_keywords(alias):
	""" Select default keywords """

	# - Select list
	keywords= []
	if alias=="radio":
		keywords= KEYWORDS_DEFAULT_RADIO
	elif alias=="solar":
		keywords= KEYWORDS_DEFAULT_SOLAR
	elif alias=="exoplanets":
		keywords= KEYWORDS_DEFAULT_EXOPLANETS
	elif alias=="ml":
		keywords= KEYWORDS_DEFAULT_ML
	else:
		logger.warning(f"keyword alias ({alias}) not recognized, returning empty list of keywords!")
		return []
		
	# - Return list without duplicates
	return list(set(keywords))


KEYWORDS_DEFAULT_ML = [
	'machine learning', 
	'deep learning', 
	'supervised learning', 
	'unsupervised learning', 
	'semi-supervised learning', 
	'semisupervised learning', 
	'self-supervised learning', 
	'self supervised', 
	'neural network', 
	'visual transformer', 
	'LLM'
]

KEYWORDS_DEFAULT_SOLAR = [
	# == CUSTOM keywords ==
	#'solar physics',
	#'solar mission',
	#'space weather',
	#'solar wind',
	#'sunspots',
	#'solar flares',
	#'coronal mass ejections',
	#'faculae',
	# == MNRAS keywords (https://academic.oup.com/DocumentLibrary/mnras/keywords.pdf) ==
	'Sun: abundances',
	'Sun: activity',
	'Sun: atmosphere',
	'Sun: chromosphere',
	'Sun: corona',
	'Sun: coronal mass ejections (CMEs)',
	'Sun: evolution',
	'Sun: faculae, plages',
	'Sun: filaments, prominences',
	'Sun: flares',
	'Sun: fundamental parameters',
	'Sun: general',
	'Sun: granulation',
	'Sun: helioseismology',
	'Sun: heliosphere',
	'Sun: infrared',
	'Sun: interior',
	'Sun: magnetic fields',
	'Sun: oscillations',
	'Sun: particle emission',
	'Sun: photosphere',
	'Sun: radio radiation',
	'Sun: rotation',
	'(Sun:) solar–terrestrial relations',
	'(Sun:) solar wind',
	'(Sun:) sunspots',
	'Sun: transition region',
	'Sun: UV radiation',
	'Sun: X-rays, gamma-rays',
	# == A&A keywords (https://www.aanda.org/author-information/information-files/170-aaa-keywords) ==
	#'Sun: abundances',
	#'Sun: activity',
	#'Sun: atmosphere',
	#'Sun: chromosphere',
	#'Sun: corona',
	#'Sun: coronal mass ejections (CMEs)',
	#'Sun: evolution',
	#'Sun: faculae, plages',
	#'Sun: filaments, prominences',
	#'Sun: flares',
	#'Sun: fundamental parameters',
	#'Sun: general',
	#'Sun: granulation',
	#'Sun: helioseismology',
	#'Sun: heliosphere',
	#'Sun: infrared',
	#'Sun: interior',
	#'Sun: magnetic fields',
	#'Sun: oscillations',
	#'Sun: particle emission',
	#'Sun: photosphere',
	#'Sun: radio radiation',
	#'Sun: rotation',
	#'(Sun:) solar-terrestrial relations',
	#'(Sun:) solar wind',
	#'(Sun:) sunspots',
	#'Sun: transition region',
	#'Sun: UV radiation',
	#'Sun: X-rays, gamma rays',
	# == Thesaurus (https://astrothesaurus.org/thesaurus/search-the-uat/) ==
	'Solar physics',
	'Space weather',
	'CNO anomaly',
	'Solar activity',
	'Solar cycle',
	'Sunspot cycle',
	'Solar activity cycles',
	'Solar cycle variations',
	'Solar magnetic activity cycle',
	'Sunspots',
	'Sunspot groups',
	'Sunspot number',
	'Sunspot flow',
	'Delta sunspots',
	'Prolonged sunspot minimum',
	'Bipolar sunspot groups',
	'Solar active regions',
	'Solar active region magnetic fields',
	'Solar active region velocity fields',
	'Solar active region filaments',
	'Solar magnetic fields',
	'Helioseismic pulsations',
	'Solar interior',
	'Asteroseismology',
	'Helioseismology',
	'Solar oscillations',
	'Quiet sun',
	'Active sun',
	'Solar dynamo',
	'Quiescent solar prominence',
	'Solar magnetic reconnection',
	'Solar magnetic flux emergence',
	'Solar magnetic bright points',
	'Solar abundances',
	'Solar flares',
	'Solar prominences',
	'Solar storm',
	'Solar filaments',
	'Ephemeral active regions',
	'Maunder minimum',
	'Wilson effect',
	'Wolf number',
	'Solar filament eruptions',
	'Quiescent solar prominence',
	'Solar flocculi',
	'Solar flocculus',
	'Polar crown filament',
	'Solar radio flares',
	'Solar x-ray flares',
	'Solar flare spectra',
	'Solar white-light flares',
	'Solar flare spectra',
	'Solar energetic particles',
	'Solar coronal mass ejections',
	'Solar particle emission',
	'Energetic solar particles',
	'Solar chromosphere',
	'Solar corona',
	'Solar photosphere',
	'Limb brightening',
	'Limb darkening',
	'Plages',
	'Solar spicules',
	'Alfven waves',
	'Active solar chromosphere',
	'Solar transition region',
	'Ellerman Bombs',
	'Quiet solar chromosphere',
	'Solar chromospheric heating',
	'Alfven surface waves',
	'Solar mottles',
	'Solar macrospicules',
	'Solar fibrils',
	'Solar coronal holes',
	'Solar coronal loops',
	'Solar coronal streamers',
	'Solar transition region',
	'Active solar corona',
	'Solar coronal heating',
	'Quiet solar corona',
	'Solar coronal radio emission',
	'Solar coronal seismology',
	'Solar coronal waves',
	'Solar coronal transients',
	'Solar coronal lines',
	'Solar coronal plumes',
	'Solar E coronal region',
	'Solar F coronal region',
	'Solar K coronal region',
	'Solar M coronal region',
	'Solar polar plume',
	'Solar granules',
	'Solar granulation',
	'Solar electromagnetic emission',
	'Solar extreme ultraviolet emission',
	'Solar gamma-ray emission',
	'Solar radio emission',
	'Solar ultraviolet emission',
	'Solar x-ray emission',
	'Solar EUV emission',
	'Solar γ-ray emission',
	'Solar UV emission',
	'Solar evolution',
	'Solar nebulae',
	'Solar faculae',
	'Solar facula',
	'Mesogranulation',
	'Supergranulation',
	'Solar core',
	'Solar differential rotation',
	'Solar meridional circulation',
	'Solar convective zone',
	'Solar radiative zone',
	'Helioseismic pulsations',
	'Solar mass',
	'Solar motion',
	'Solar atmospheric motions',
	'Solar antapex',
	'Solar apex',
	'Solar neutrons',
	'Solar coronal mass ejection shocks',
	'Solar neutrinos',
	'Solar CME shocks',
	'Solar radiation',
	'Solar radius',
	'Solar rotation',
	'Solar differential rotation',
	'Solar spectral irradiance',
	'Solar irradiance',
	'Solar surface',
	'Heliopause',
	'Solar wind',
	'Fast solar wind',
	'Slow solar wind',
	'Solar-planetary interactions',
	'Sun-Earth interactions',
	# == ADDON KEYWORDS ==
	'Forbush decrease',
	'GOES',
	'SDO',
	'AIA',
	'magnetogram',
	'CME',
]

KEYWORDS_DEFAULT_RADIO = [
	# == CUSTOM keywords ==
	'radioastronomy',
	'radio survey',
	'radio continuum',
	'radio lines',
	'radio sources',
	# == MNRAS keywords (https://academic.oup.com/DocumentLibrary/mnras/keywords.pdf) ==
	'radio continuum: galaxies', 
	'radio continuum: general',
	'radio continuum: ISM',
	'radio continuum: planetary systems',
	'radio continuum: stars',
	'radio continuum: transients',
	'radio lines: galaxies',
	'radio lines: general',
	'radio lines: ISM',
	'radio lines: planetary systems',
	'radio lines: stars',
	# == A&A keywords (https://www.aanda.org/author-information/information-files/170-aaa-keywords) ==
	'Radio continuum: galaxies',
	'Radio continuum: general',
	'Radio continuum: ISM',
	'Radio continuum: planetary systems',
	'Radio continuum: stars',
	'Radio lines: galaxies',
	'Radio lines: general',
	'Radio lines: ISM',
	'Radio lines: planetary systems',
	'Radio lines: stars',
	# == Thesaurus (https://astrothesaurus.org/thesaurus/search-the-uat/) ==
	'Discrete radio sources',
	'Extragalactic radio sources',
	'Fanaroff-Riley radio galaxies',
	'Flat-spectrum radio quasars',
	'Galactic radio sources',
	'Giant radio galaxies',
	'Magnetospheric radio emissions',
	'Quasi-stellar radio sources',
	'Radio active galactic nuclei',
	'Radio astrometry',
	'Radio astronomy',
	'Radio bursts',
	'Radio continuum emission',
	'Radio cores',
	'Radio galaxies',
	'Radio hot spots',
	'Radio interferometers',
	'Radio interferometry',
	'Radio jets',
	'Radio lobes',
	'Radio loud quasars',
	'Radio observatories',
	'Radio plumes',
	'Radio pulsars',
	'Radio quiet quasars',
	'Radio receivers',
	'Radio source catalogs',
	'Radio source counts',
	'Radio sources',
	'Radio spectroscopy',
	'Radio telescopes',
	'Radio transient sources',
	'Tailed radio galaxies',
	# == ADDON KEYWORDS ==
	'radio',
	'interferometry',
	'interferometric',
	'single dish',
	'vla',
	'vlbi',
	'alma',
	'SKA',
	'Square Kilometer Array',
	'LOFAR',
	'ASKAP',
	'MeerKAT',
	'radio galaxy',
	'radio image',
	'radio morphology',
]


KEYWORDS_DEFAULT_EXOPLANETS = [
	# == CUSTOM keywords ==

	# == MNRAS keywords (https://academic.oup.com/DocumentLibrary/mnras/keywords.pdf) ==
	
	# == A&A keywords (https://www.aanda.org/author-information/information-files/170-aaa-keywords) ==
	
	# == Thesaurus (https://astrothesaurus.org/thesaurus/search-the-uat/) ==
	
	# == ADDON KEYWORDS ==
	'exoplanet',
	'planet',
	'transit',
	'radial velocity',
	'kepler',
	'tess',
	'plato',
	'atmosphere',
	'light curve',
	'habitable',
]

